// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PanierAPI;

#nullable disable

namespace PanierAPI.Migrations
{
    [DbContext(typeof(PanierDbContext))]
    [Migration("20230430220123_ListProduitIdDansPanier")]
    partial class ListProduitIdDansPanier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PanierAPI.Models.Panier", b =>
                {
                    b.Property<Guid>("PanierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PanierId");

                    b.ToTable("Paniers");
                });

            modelBuilder.Entity("PanierAPI.Models.ProduitIds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ProduitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ProduitIds");
                });

            modelBuilder.Entity("PanierProduitIds", b =>
                {
                    b.Property<Guid>("PanierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProduitIdListeId")
                        .HasColumnType("int");

                    b.HasKey("PanierId", "ProduitIdListeId");

                    b.HasIndex("ProduitIdListeId");

                    b.ToTable("PanierProduit", (string)null);
                });

            modelBuilder.Entity("PanierProduitIds", b =>
                {
                    b.HasOne("PanierAPI.Models.Panier", null)
                        .WithMany()
                        .HasForeignKey("PanierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PanierAPI.Models.ProduitIds", null)
                        .WithMany()
                        .HasForeignKey("ProduitIdListeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
