// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PanierAPI;

#nullable disable

namespace PanierAPI.Migrations
{
    [DbContext(typeof(PanierDbContext))]
    [Migration("20230428211851_ListGuidVersListProduitIds")]
    partial class ListGuidVersListProduitIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PanierAPI.Models.Panier", b =>
                {
                    b.Property<Guid>("PanierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PanierId");

                    b.ToTable("Paniers");
                });

            modelBuilder.Entity("PanierAPI.Models.ProduitIds", b =>
                {
                    b.Property<Guid>("ProduitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PanierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProduitId");

                    b.HasIndex("PanierId");

                    b.ToTable("ProduitIds");
                });

            modelBuilder.Entity("PanierAPI.Models.ProduitIds", b =>
                {
                    b.HasOne("PanierAPI.Models.Panier", null)
                        .WithMany("ProduitIdListe")
                        .HasForeignKey("PanierId");
                });

            modelBuilder.Entity("PanierAPI.Models.Panier", b =>
                {
                    b.Navigation("ProduitIdListe");
                });
#pragma warning restore 612, 618
        }
    }
}
