// <auto-generated />
using System;
using FactureAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FactureAPI.Migrations
{
    [DbContext(typeof(FactureDbContext))]
    [Migration("20230426180750_ModifModelFacture")]
    partial class ModifModelFacture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FactureAPI.Models.Facture", b =>
                {
                    b.Property<Guid>("FactureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTimeDay")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PanierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PrixTotal")
                        .HasColumnType("float");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FactureId");

                    b.ToTable("Factures");
                });
#pragma warning restore 612, 618
        }
    }
}
